### ISSUE TITLE
Base64Decode is panic

### ISSUE THREAD

**Issue by xiekeyi98** [pingcap/tidb-ctl#15]
```
xiekeyi@ubuntu:~/gopath/src/github.com/pingcap/tidb-ctl$ git fetch upstream master
来自 https://github.com/pingcap/tidb-ctl
 * branch            master     -> FETCH_HEAD
xiekeyi@ubuntu:~/gopath/src/github.com/pingcap/tidb-ctl$ git reset --hard upstream/master 
HEAD 现在位于 bef868e Add API to evict owner in etcd (#14)
xiekeyi@ubuntu:~/gopath/src/github.com/pingcap/tidb-ctl$ git status
位于分支 master
您的分支领先 'origin/master' 共 1 个提交。
  （使用 "git push" 来发布您的本地提交）

未跟踪的文件:
  （使用 "git add <文件>..." 以包含要提交的内容）

	tidb-ctl

提交为空，但是存在尚未跟踪的文件（使用 "git add" 建立跟踪）
xiekeyi@ubuntu:~/gopath/src/github.com/pingcap/tidb-ctl$ go version
go version go1.12 linux/amd64
xiekeyi@ubuntu:~/gopath/src/github.com/pingcap/tidb-ctl$ make
CGO_ENABLED=0 GO111MODULE=on go build
xiekeyi@ubuntu:~/gopath/src/github.com/pingcap/tidb-ctl$ ./tidb-ctl base64decode dGhpcyBpcyBhIGV4YW1wbGU=
hex: 
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/pingcap/tidb-ctl/cmd.base64decode(0xd0c320, 0xc000089240, 0x1, 0x1, 0x0, 0x0)
	/home/xiekeyi/gopath/src/github.com/pingcap/tidb-ctl/cmd/base64decode.go:50 +0x428
github.com/spf13/cobra.(*Command).execute(0xd0c320, 0xc0000891f0, 0x1, 0x1, 0xd0c320, 0xc0000891f0)
	/home/xiekeyi/gopath/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:698 +0x431
github.com/spf13/cobra.(*Command).ExecuteC(0xd0d860, 0xa, 0x28, 0x25)
	/home/xiekeyi/gopath/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:783 +0x29f
github.com/spf13/cobra.(*Command).Execute(...)
	/home/xiekeyi/gopath/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:736
github.com/pingcap/tidb-ctl/cmd.Execute()
	/home/xiekeyi/gopath/src/github.com/pingcap/tidb-ctl/cmd/root.go:77 +0x32
main.main()
	/home/xiekeyi/gopath/src/github.com/pingcap/tidb-ctl/main.go:19 +0x20
xiekeyi@ubuntu:~/gopath/src/github.com/pingcap/tidb-ctl$ 

```

**Comment by xiekeyi98** [comment]
I will work on this.
(I am not access to assign this issue to myself)

**Comment by imtbkcat** [comment]
usage:

```
./tidb-ctl base64decode -v cAAAAAABX+s=
hex: 7000000000015feb
uint64: 8070450532248018923
```
